version: '3.8'
services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-web-config:/etc/odoo
    restart: always
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  odoo-web-data:
  odoo-web-config:
  odoo-db-data:
