version: '3.1'
services:
  web:
    image: vuna2004/docker-odoo:16.0-arm64
		restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:15
		restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
